# CMake generated Testfile for 
# Source directory: /mnt/c/Users/enlan/University/York/Dissertation/Repositories/BOUT-dev/examples
# Build directory: /mnt/c/Users/enlan/University/York/Dissertation/Repositories/Dissertation_Project/test-build/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs("2Dturbulence_multigrid")
subdirs("6field-simple")
subdirs("IMEX/advection-diffusion")
subdirs("IMEX/advection-reaction")
subdirs("IMEX/diffusion-nl")
subdirs("IMEX/drift-wave")
subdirs("IMEX/drift-wave-constraint")
subdirs("advdiff")
subdirs("advdiff2")
subdirs("backtrace")
subdirs("blob2d")
subdirs("blob2d-outerloop")
subdirs("blob2d-laplacexz")
subdirs("boundary-conditions/advection")
subdirs("conducting-wall-mode")
subdirs("conduction")
subdirs("conduction-snb")
subdirs("constraints/alfven-wave")
subdirs("constraints/laplace-dae")
subdirs("dalf3")
subdirs("eigen-box")
subdirs("elm-pb")
subdirs("elm-pb-outerloop")
subdirs("em-drift")
subdirs("fci-wave")
subdirs("fci-wave-logn")
subdirs("finite-volume/diffusion")
subdirs("finite-volume/fluid")
subdirs("finite-volume/test")
subdirs("gas-compress")
subdirs("gravity_reduced")
subdirs("gyro-gem")
subdirs("hasegawa-wakatani")
subdirs("hasegawa-wakatani-3d")
subdirs("invertable_operator")
subdirs("jorek-compare")
subdirs("lapd-drift")
subdirs("laplacexy/alfven-wave")
subdirs("laplacexy/laplace_perp")
subdirs("laplacexy/simple")
subdirs("laplacexy/simple-hypre")
subdirs("monitor")
subdirs("monitor-newapi")
subdirs("orszag-tang")
subdirs("preconditioning/wave")
subdirs("reconnect-2field")
subdirs("shear-alfven-wave")
subdirs("staggered_grid")
subdirs("subsampling")
subdirs("tokamak-2fluid")
subdirs("uedge-benchmark")
subdirs("wave-slab")
