# CMake generated Testfile for 
# Source directory: /mnt/c/Users/enlan/University/York/Dissertation/Repositories/BOUT-dev/tests/integrated
# Build directory: /mnt/c/Users/enlan/University/York/Dissertation/Repositories/Dissertation_Project/test-build/tests/integrated
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs("test-backtrace")
subdirs("test-beuler")
subdirs("test-boutpp")
subdirs("test-bout-override-default-option")
subdirs("test-command-args")
subdirs("test-communications")
subdirs("test-coordinates-initialization")
subdirs("test-cyclic")
subdirs("test-delp2")
subdirs("test-datafilefacade")
subdirs("test-drift-instability")
subdirs("test-drift-instability-staggered")
subdirs("test-fieldgroupComm")
subdirs("test-griddata")
subdirs("test-griddata-yboundary-guards")
subdirs("test-gyro")
subdirs("test-initial")
subdirs("test-interchange-instability")
subdirs("test-interpolate")
subdirs("test-interpolate-z")
subdirs("test-invertable-operator")
subdirs("test-invpar")
subdirs("test-laplace")
subdirs("test-laplace-petsc3d")
subdirs("test-laplace-hypre3d")
subdirs("test-laplacexy2-hypre")
subdirs("test-laplacexy-fv")
subdirs("test-laplacexy-short")
subdirs("test-laplacexz")
subdirs("test-multigrid_laplace")
subdirs("test-naulin-laplace")
subdirs("test-options-netcdf")
subdirs("test-petsc_laplace")
subdirs("test-petsc_laplace_MAST-grid")
subdirs("test-restart-io")
subdirs("test-restarting")
subdirs("test-slepc-solver")
subdirs("test-smooth")
subdirs("test-snb")
subdirs("test-solver")
subdirs("test-squash")
subdirs("test-stopCheck")
subdirs("test-stopCheck-file")
subdirs("test-twistshift")
subdirs("test-twistshift-staggered")
subdirs("test-vec")
subdirs("test-yupdown")
subdirs("test-yupdown-weights")
